# Generated by Django 5.2.7 on 2026-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('signal', models.CharField(max_length=20)),
                ('confidence', models.IntegerField()),
                ('target', models.FloatField()),
                ('stop_loss', models.FloatField()),
            ],
        ),
    ]
