import { useNavigate } from "react-router-dom";
import "../style/home.css";
function Home() {
  let nav=useNavigate();
  let movedata =()=>{
    nav("/fetch/")
  }


  return (
    <div className="home">
      <section className="hero">
        <div className="hero-content">
          <h1>Smart Decisions. Powered by Data.</h1>
          <p>"Money is a terrible master but an excellent servant"</p>

          <div className="hero-buttons">
            <button className="primary-btn" onClick={movedata}>Analyze Stock</button>
            
          </div>
        </div>
      </section>
      <div className="ticker">
        <marquee behavior="" direction="left" scrollamount="10">TATASTEEL.NS ↑ +1.25% &nbsp;&nbsp;
          RELIANCE.NS ↓ -0.45% &nbsp;&nbsp;
          INFY.NS ↑ +0.90% &nbsp;&nbsp;
          HDFCBANK.NS ↑ +0.30%</marquee>
      </div>

      <section className="features">
        <h2>Features</h2>
        <div className="feature-grid">
          <div className="card">
            <h3>Decision making</h3>
            <p>Buy/Sell recommendations using historical data analysis.</p>
          </div>
          <div className="card">
            <h3>Risk Management</h3>
            <p>Target & Stop Loss automatically calculated.</p>
          </div>
          <div className="card">
            <h3>Confidence Score</h3>
            <p>Each decision includes probability-based accuracy.</p>
          </div>
        </div>
      </section>

      <section className="how">
        <h2>How It Works</h2>
        <div className="steps">
          <div className="step">
            <h3>1. Enter Stock</h3>
            <p>Provide NSE/BSE stock code.</p>
          </div>
          <div className="step">
            <h3>2. Get Decision</h3>
            <p>Receive signal, target & stop loss instantly.</p>
          </div>
          <div className="step">
            <h3>3. View History</h3>
            <p>Visualization past history to Present day.</p>
          </div>
        </div>
      </section>

      <div className="disclaimer">
        Disclaimer:This application is built strictly for educational and analytical purposes.
The signals generated by this system are based on technical indicators and historical market data and do not constitute financial or investment advice.
      </div>
      

    </div>
  );
}

export default Home;
